const express = require('express');
const helmet = require('helmet');
const cors = require('cors');
const session = require('express-session'); // 1.add this

const db = require('../database/dbConfig');
// const KnexSessionStore = require('connect-session-knex');

// KnexSessionStore(session);
// or:
const KnexSessionStore = require('connect-session-knex')(session);

const authRouter = require('../auth/auth-router.js');
const usersRouter = require('../users/users-router.js');

const server = express();

// 3.add this
const sessionConfig = {
 name: 'monkey',
 secret: 'keep it secret, keep it safe',
 cookie: {
  maxAge: 1000 * 60 * 10, // in ms available (15 min)
  //   maxAge: 1000 * 60 * 60 * 24, // in ms available (24 hours)
  secure: false, // used over http only 'false' for development
  httpOnly: true, // cannot access the cookie
 },
 // can the user access the cookie from js using document.cookie
 resave: false, //
 saveUninitialized: false, // GDPR laws against setting cookies automatically
 store: new KnexSessionStore({
  // using connect-session-knex library - inside db doesn't go inside your browser
  knex: db, // asks knex if we have this file (config)
  tablename: 'sessions', // save session if server restarts - persist data in db
  sidfieldname: 'sid', // pass session id - generated by the library
  createtable: true, // if the table doesn't exists, creates table
  clearInterval: 1000 * 60 * 60, // in ms - 1 hour
 }),
};

server.use(session(sessionConfig)); // 2. add this

server.use(helmet());
server.use(express.json());
server.use(cors());

server.use('/api/auth', authRouter);
server.use('/api/users', usersRouter);

server.get('/', (req, res) => {
 res.send("It's alive!");
});

module.exports = server;
